# -*- coding: utf-8 -*-
"""05_Statistical Visualization Plots-Q2_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YLOtV2IrxK6DfFvVQMKVRk-tYL2GNDF0

**EXPLORATORY DATA ANALYSIS - DATA VISUALIZATION**

The data that we indent to work with can be in any format, and it is imperative to do the EDA and Preprocess on it. A key element in determining the details or intricacies of the data involve in visualizing the data.

A few of the plots are:

  1. Histogram - which is primarily used to check whether the data is normal or has a uniform curve or not. It also gives 
  insights for the skewness and kurtosis of the data.
  
  2. Box Plot - A plot extensively used to determine the extreme values, commonly known as Outliers in the data. 
  Seeing the plot we can infer whether the data is normally distributed as well or not.

Q1) Calculate Skewness, Kurtosis using R/Python code & draw inferences on the following data.

Hint: [Insights to be drawn from the data such as data is normally distributed, outliers, measures like mean, median, mode, 
    variance, std. deviation are to calculated]
    
    
   b. Top speed and Weight
"""

#Import the dataset
import pandas as pd

Q2_b = pd.read_csv("Q2_b.csv")

Q2_b.head()

# Import stats sub-module for statistical analysis 

from scipy import stats

# Import library for visualizations
import matplotlib.pyplot as plt

# Plot the histogram
plt.hist(Q2_b.SP)

''' Notice the plot for normality observe the skewness in the data. Observe the peakedness to assess the kurtosis'''

plt.hist(Q2_b.WT)

''' Notice the plot for normality observe the skewness in the data. Observe the peakedness to assess the kurtosis'''

"""**Perform EDA: The 4 Moment of Business Decisions**

First Moment of Business Decision also called the Measured of Central Tendency include:
    
    Mean
    Median
    Mode
"""

# Mean 
Q2_b.SP.mean() # code for mean of the column/feature - 'Top speed' in Q2_b dataset

Q2_b.WT.mean() # code for mean of the column/feature - 'Weight' in Q2_b dataset

# Median
Q2_b.SP.median()

Q2_b.WT.median()

# Mode
Q2_b.SP.mode()

Q2_b.WT.mode()

"""**Second Moment of Business Decision - Measures of Dispersion**

1. Variance - The average spread of the data from the mean, calculated using squared values. 
2. Standard deviation - Represents the magnitude of the average spread (root of the Variance values).
3. Range - Represents the boundaries, the difference of the max and min point/values of the data.
"""

# Variance
Q2_b.SP.var()

Q2_b.WT.var()

# Standard Deviation
Q2_b.SP.std()

Q2_b.WT.std()

# Third Moment Business Decision - SKEWNESS: a measure of asymmetry in the data
Q2_b.SP.skew()

Q2_b.WT.skew()

# Fourth Moment Business Decision - KURTOSIS: a measure of peakedness in the data
Q2_b.SP.kurt()

Q2_b.WT.kurt()

"""**Outlier detection using Boxplot**"""

# Plot the boxplot for the individual columns
plt.boxplot(Q2_b.SP)

plt.boxplot(Q2_b.WT)

"""**Notice that both the features Top speed and Weight have outliers. This can be treated using the 3R technique, either Retain the outlier depending on the data. Rectify it using Winsorization or Remove using Trimming apprach.**

**SOLUTION**

•	Skewness (Top Speed) = 1.581454 and Skewness (Weight) = -0.6033099

•	Kurtosis (Top Speed) = 5.723521 and Kurtosis (Weight) = 3.819466

•	Data is not normally distributed as it has skewness for both the columns

•	Mean (Top Speed)= 121.5403 and Mean (Weight) = 32.41258

•	Median (Top Speed) = 118.2087 and Median (Weight) = 32.73452

•	Variance (Top Speed) = 201.113 and Variance (Weight) = 56.14225

•	Std deviation (Top Speed) = 14.18143 and Std deviation (Weight) = 7.492813

•	There are outliers in Top speed column as well as in Weight column
"""

