# -*- coding: utf-8 -*-
"""05_Statistical Visualization Plots-Q1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TMdizbg_APpjYpY6zuhN1jrlv330ijYO

**EXPLORATORY DATA ANALYSIS - DATA VISUALIZATION**

The data that we indent to work with can be in any format, and it is imperative to do the EDA and Preprocess on it. A key element in determining the details or intricacies of the data involve in visualizing the data.

A few of the plots are:

  1. Histogram - which is primarily used to check whether the data is normal or has a uniform curve or not. It also gives 
  insights for the skewness and kurtosis of the data.
  
  2. Box Plot - A plot extensively used to determine the extreme values, commonly known as Outliers in the data. 
  Seeing the plot we can infer whether the data is normally distributed as well or not.

Q1) Calculate Skewness, Kurtosis using Python & draw inferences on the following data.

Hint: [Insights to be drawn from the data such as data is normally distributed, outliers, measures like mean, median, mode, 
    variance, std. deviation are to calculated]
    
   a.   Cars Data: speed and distance
"""

# Import the dataset
import pandas as pd

Q1_a = pd.read_csv("Q1_a.csv")

Q1_a.head()

# Import stats sub-module for statistical analysis 

from scipy import stats

# Import library for visualizations
import matplotlib.pyplot as plt

# Plot the histogram
plt.hist(Q1_a.speed)

''' Notice the plot for normality observe the skewness in the data. Observe the peakedness to assess the kurtosis'''

plt.hist(Q1_a.dist)

''' Notice the plot for normality observe the skewness in the data. Observe the peakedness to assess the kurtosis'''

"""**Perform EDA: The 4 Moment of Business Decisions**

First Moment of Business Decision also called the Measured of Central Tendency include:
    
    Mean
    Median
    Mode
"""

# Mean 
Q1_a.speed.mean() # code for mean of the column/feature - 'speed' in Q1_a dataset

Q1_a.dist.mean() # code for mean of the column/feature - 'dist' in Q1_a dataset

# Median
Q1_a.speed.median()

Q1_a.dist.median()

# Mode
Q1_a.speed.mode()

Q1_a.dist.mode()

"""Second Moment of Business Decision - Measures of Dispersion

1. Variance - The average spread of the data from the mean, calculated using squared values. 
2. Standard deviation - Represents the magnitude of the average spread (root of the Variance values).
3. Range - Represents the boundaries, the difference of the max and min point/values of the data.

"""

# Variance
Q1_a.speed.var()

Q1_a.dist.var()

# Standard Deviation
Q1_a.speed.std()

Q1_a.dist.std()

# Third Moment Business Decision - SKEWNESS: a measure of asymmetry in the data
Q1_a.speed.skew()

Q1_a.dist.skew()

# Fourth Moment Business Decision - KURTOSIS: a measure of peakedness in the data
Q1_a.speed.kurt()

Q1_a.dist.kurt()

"""**Outlier detection using Boxplot**"""

# Plot the boxplot for the individual columns
plt.boxplot(Q1_a.speed)

"""**Notice the data for outliers. Additionally we can observe for the normal distribution**"""

plt.boxplot(Q1_a.dist)

"""**Notice that the 'dist' feature has one outlier. This can be treated using the 3R technique, either Retain the outlier depending on the data. Rectify it using Winsorization or Remove using Trimming apprach.**

**SOLUTION**

•	Skewness(Speed) = -0.1139548 and Skewness(dist) = 0.7824835

•	Kurtosis(Speed) = -.508994 and Kurtosis(dist) = 0.4050525

•	Data is not normally distributed as it has skewness for both the columns.

•	Mean(Speed)= 15.4 and Mean(dist) = 42.98

•	Median(Speed) = 15 and Median(dist) = 36

•	Variance(Speed) = 27.95918 and Variance(dist) = 664.0608

•	Std deviation(Speed) = 5.287644 and Std deviation(Speed) = 25.76938 

•	There is no outlier in speed column but there is at least 1 outlier present in distance column.
"""